#!/usr/bin/env python3
"""Plot training curves for all PCDiff experiments (V12, V13, V14, long training).

Generated by ML Researcher agent for DIM-50.
"""
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Load data
DATA_FILE = Path(__file__).parent / "training_logs.json"
with open(DATA_FILE) as f:
    data = json.load(f)

# Color scheme
COLORS = {
    "long_v7_002": "#888888",
    "exp_v12_001_vpred": "#e74c3c",
    "exp_v12_002_minsnr": "#3498db",
    "exp_v12_003_ema": "#2ecc71",
    "exp_v12_004_cosine": "#9b59b6",
    "exp_v12_005_combined": "#e67e22",
    "exp_v12_006_augment": "#1abc9c",
    "exp_v12_007_best_combined": "#c0392b",
    "long_v14_cosine_minsnr": "#2980b9",
    "exp_v13_1": "#f39c12",
    "exp_v13_2": "#d35400",
    "exp_v13_3": "#16a085",
    "exp_v13_4": "#8e44ad",
    "exp_v13_5": "#27ae60",
}

OUT_DIR = Path(__file__).parent / "plots"
OUT_DIR.mkdir(exist_ok=True)


def get_xy(exp_key, field):
    """Extract (epoch, value) pairs."""
    if exp_key not in data:
        return [], []
    epochs = data[exp_key]["epochs"]
    x = [e["epoch"] for e in epochs if field in e]
    y = [e[field] for e in epochs if field in e]
    return x, y


# ============================================================
# Plot 1: V12 Short Experiments — Training Loss (0-50 epochs)
# ============================================================
fig, ax = plt.subplots(figsize=(12, 7))
v12_short = [
    ("long_v7_002", "--"),
    ("exp_v12_001_vpred", "-"),
    ("exp_v12_002_minsnr", "-"),
    ("exp_v12_003_ema", "-"),
    ("exp_v12_004_cosine", "-"),
    ("exp_v12_005_combined", "-"),
    ("exp_v12_006_augment", "-"),
]
for key, ls in v12_short:
    x, y = get_xy(key, "train_loss")
    if x:
        label = data[key]["label"]
        ax.plot(x, y, ls, color=COLORS.get(key, "gray"), label=label, linewidth=2, marker="o", markersize=4)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Training Loss", fontsize=13)
ax.set_title("V12 Individual Technique Experiments — Training Loss", fontsize=14, fontweight="bold")
ax.legend(fontsize=10, loc="upper right")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 55)
fig.tight_layout()
fig.savefig(OUT_DIR / "v12_short_train_loss.png", dpi=150)
plt.close()
print("Saved v12_short_train_loss.png")


# ============================================================
# Plot 2: V12 Short Experiments — Validation Loss (at epoch 50)
# ============================================================
fig, ax = plt.subplots(figsize=(10, 6))
v12_val = []
for key, _ in v12_short:
    x, y = get_xy(key, "val_loss")
    if y:
        v12_val.append((data[key]["label"], y[-1]))

if v12_val:
    labels, vals = zip(*sorted(v12_val, key=lambda x: x[1]))
    colors_bar = ["#2ecc71" if v < 0.3 else "#f39c12" if v < 0.4 else "#e74c3c" for v in vals]
    ax.barh(labels, vals, color=colors_bar, edgecolor="black", linewidth=0.5)
    ax.set_xlabel("Validation Loss (lower is better)", fontsize=12)
    ax.set_title("V12 Techniques — Validation Loss Comparison (epoch 50)", fontsize=13, fontweight="bold")
    for i, v in enumerate(vals):
        ax.text(v + 0.01, i, f"{v:.3f}", va="center", fontsize=10)
    ax.set_xlim(0, max(vals) * 1.15)
    fig.tight_layout()
fig.savefig(OUT_DIR / "v12_val_loss_comparison.png", dpi=150)
plt.close()
print("Saved v12_val_loss_comparison.png")


# ============================================================
# Plot 3: Long Training Curves — Training Loss (0-600+ epochs)
# ============================================================
fig, ax = plt.subplots(figsize=(14, 7))
long_exps = [
    ("long_v7_002", "--"),
    ("exp_v12_007_best_combined", "-"),
    ("long_v14_cosine_minsnr", "-"),
]
for key, ls in long_exps:
    x, y = get_xy(key, "train_loss")
    if x:
        ax.plot(x, y, ls, color=COLORS.get(key, "gray"), label=data[key]["label"], linewidth=2, alpha=0.8)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Training Loss", fontsize=13)
ax.set_title("Long Training — Training Loss Over Time", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(OUT_DIR / "long_training_loss.png", dpi=150)
plt.close()
print("Saved long_training_loss.png")


# ============================================================
# Plot 4: Long Training — Validation Loss
# ============================================================
fig, ax = plt.subplots(figsize=(14, 7))
for key, ls in long_exps:
    x, y = get_xy(key, "val_loss")
    if x:
        ax.plot(x, y, ls + "o", color=COLORS.get(key, "gray"), label=data[key]["label"],
                linewidth=2, markersize=6, alpha=0.8)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Validation Loss", fontsize=13)
ax.set_title("Long Training — Validation Loss Over Time", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(OUT_DIR / "long_training_val_loss.png", dpi=150)
plt.close()
print("Saved long_training_val_loss.png")


# ============================================================
# Plot 5: Long Training — Best Training Loss (envelope)
# ============================================================
fig, ax = plt.subplots(figsize=(14, 7))
for key, ls in long_exps:
    x, y = get_xy(key, "best_loss")
    if x:
        ax.plot(x, y, ls, color=COLORS.get(key, "gray"), label=data[key]["label"], linewidth=2.5)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Best Training Loss (monotonic decrease)", fontsize=13)
ax.set_title("Long Training — Best Training Loss Over Time", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(OUT_DIR / "long_training_best_loss.png", dpi=150)
plt.close()
print("Saved long_training_best_loss.png")


# ============================================================
# Plot 6: V13 Combination Experiments — Training Loss
# ============================================================
fig, ax = plt.subplots(figsize=(12, 7))
v13_exps = [
    "exp_v13_1", "exp_v13_2", "exp_v13_3", "exp_v13_4", "exp_v13_5"
]
for key in v13_exps:
    x, y = get_xy(key, "train_loss")
    if x:
        ax.plot(x, y, "-o", color=COLORS.get(key, "gray"), label=data[key]["label"],
                linewidth=2, markersize=4)

# Add V12 baselines for reference
for ref_key in ["exp_v12_004_cosine", "exp_v12_003_ema"]:
    x, y = get_xy(ref_key, "train_loss")
    if x:
        ax.plot(x, y, "--", color=COLORS.get(ref_key, "gray"), label=data[ref_key]["label"] + " (ref)",
                linewidth=1.5, alpha=0.5)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Training Loss", fontsize=13)
ax.set_title("V13 Combination Experiments — Training Loss", fontsize=14, fontweight="bold")
ax.legend(fontsize=9, loc="upper right")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 55)
fig.tight_layout()
fig.savefig(OUT_DIR / "v13_train_loss.png", dpi=150)
plt.close()
print("Saved v13_train_loss.png")


# ============================================================
# Plot 7: Learning Rate Schedule Comparison
# ============================================================
fig, ax = plt.subplots(figsize=(14, 7))
for key, ls in long_exps:
    x, y = get_xy(key, "lr")
    if x:
        ax.plot(x, y, ls, color=COLORS.get(key, "gray"), label=data[key]["label"], linewidth=2)

ax.set_xlabel("Epoch", fontsize=13)
ax.set_ylabel("Learning Rate", fontsize=13)
ax.set_title("Learning Rate Schedule — Long Training Runs", fontsize=14, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
ax.set_yscale("log")
fig.tight_layout()
fig.savefig(OUT_DIR / "lr_schedules.png", dpi=150)
plt.close()
print("Saved lr_schedules.png")


# ============================================================
# Plot 8: All Experiments — Final Validation Loss Summary
# ============================================================
fig, ax = plt.subplots(figsize=(12, 8))
all_val = []
for key, exp in data.items():
    epochs = exp["epochs"]
    val_epochs = [e for e in epochs if "val_loss" in e]
    if val_epochs:
        best_val = min(e["val_loss"] for e in val_epochs)
        all_val.append((exp["label"], best_val, key))

if all_val:
    all_val.sort(key=lambda x: x[1])
    labels, vals, keys = zip(*all_val)
    colors_bar = [COLORS.get(k, "#95a5a6") for k in keys]
    bars = ax.barh(labels, vals, color=colors_bar, edgecolor="black", linewidth=0.5)
    ax.set_xlabel("Best Validation Loss (lower is better)", fontsize=12)
    ax.set_title("All Experiments — Best Validation Loss", fontsize=14, fontweight="bold")
    for i, v in enumerate(vals):
        ax.text(v + 0.005, i, f"{v:.4f}", va="center", fontsize=9)
    ax.set_xlim(0, max(vals) * 1.15)
    fig.tight_layout()
fig.savefig(OUT_DIR / "all_experiments_val_loss.png", dpi=150)
plt.close()
print("Saved all_experiments_val_loss.png")

print("\n=== All plots saved to", OUT_DIR, "===")
